### PR TITLE
fix(format-to-jsx): use "key in dict" to tell if key is found

### PR DESCRIPTION
**Pull request by PoomSmart**
Using `if (replaceValue) { ... }` will yield the false positive: "0" or zero as a number. We prevent that by a more accurate key-in-dictionary check.

### CODE REVIEW

**Comment by PoomSmart** [comment]
@matmalkowski Reverted. The change left is just spacing or something irrelevant.

**Comment by matmalkowski** [comment]
@PoomSmart Please also create a new PR for i18n-jsx once this package gets published and update the dependency as a fix to it as well!

**Pull request merged**
